package com.stawisha.maziwa.erpz.model;

/**
 *
 * @author samuel
 */
public enum Roles {
    VIEW_MILK_RECORDS,
    UPDATE_MILK_RECORDS,
    DELETE_MILK_RECORDS,
    INSERT_MILK_RECORDS,
    VIEW_MEMBER_INFORMATION,
    UPDATE_MEMBER_INFORMATION,
    DELETE_MEMBER_INFORMATION,
    INSERT_MEMBER_INFORMATION,
    VIEW_EMPLOYEE_INFORMATION,
    UPDATE_EMPLOYEE_INFORMATION,
    DELETE_EMPLOYEE_INFORMATION,
    INSERT_EMPLOYEE_INFORMATION,
    VIEW_ANNUAL_REPORTS,
    VIEW_YEAR_REPORTS,
    VIEW_MONTHLY_REPORTS,
    VIEW_DAILY_REPORTS
}
